### ISSUE TITLE
Accept DEM input with different projections

### ISSUE THREAD

**Issue by SophiaUP** [SophiaUP/SoilDataPrep#1]
It would be more user-friendly to allow the DEM input with differnt projections.
"projectRaster" allows to change the projection of a raster in R, but it was not possible to apply this to large catchments. Dividing the catchment into several tiles made the projection possible. Nevertheless, trying to reassemble the tiles resulted in error.
Thus, up to now the DEM input for SoilDataPrep must be provided as WGS84, longlat.

**Comment by TillF** [comment]
I added the reprojection to be dine only when necessary. Thus, if ther catchment is too large to cause mem problems, on just has to  project manually first. Can be closed.

**Comment by SophiaUP** [comment]
ok, that sounds good.
