### ISSUE TITLE
Ein Bodentyp fehlt in soil.dat

### ISSUE THREAD

**Issue by TillF** [SophiaUP/SoilDataPrep#3]
Im Esera-Datensatz sind in der Karte (soils_catchment.tif) 13 Bodenarten vorhanden:
27
28
72
79
98
1001
1011
1027
1030
1067
1072
1079
1098

In soil.dat (ehemals soils.txt) sind es aber nur 12, es fehlt die Nummer 28, ebenso in horizons.txt und 
r_soil_contains_particles.txt.
Diese ist allerdings auch nur in geringem Umfang und sehr eigenartig vorhanden (gelbe Flächen in Abb.)
![soil28](https://user-images.githubusercontent.com/11060560/41963439-e2eefe9c-79f7-11e8-8090-3745d7d64434.png)

**Comment by SophiaUP** [comment]
Komisch, ich hab mir das neue Ergebnis angeschaut und diesmal taucht Boden Nummer 28 gar nicht mehr auf. Außerdem ist die Verteilung der Bodentypen ganz anders als in deiner Grafik, mir erscheint sie auch realistischer. Kurzum das Problem scheint gelöst : ).

![soils_catchment](https://user-images.githubusercontent.com/35838674/47229186-70401280-d3c7-11e8-9abd-4a735de0adda.png)

**Comment by TillF** [comment]
OK, konnte den Fehler auch nicht mehr repoduzieren.
