### ISSUE TITLE
OM very high

### ISSUE THREAD

**Issue by TillF** [SophiaUP/SoilDataPrep#4]
The OM-content for the soils in Esera ranges between 9 and 33 %. This seems very high, please check.

**Comment by SophiaUP** [comment]
Soil.dat uses the OM content only from the top soil layer. The lower soil layers have much lower values (means per soil layer mostly among 2.5 %, max 9 %).
It seems to me realistic (I did a short search) that OM is considerably higher in the top soil layer (up to 10 or 20 cm), and then decreases strongly.
I remember that before you were using just 2 different soil layers and now we have 7, of which the top layer (sl1) is very thin: 2.5 cm. Therefor I think that these high values could be ok, but if we need for WASA an OM value which goes deeper, we could use the mean of some of the upper soil layers

**Comment by TillF** [comment]
You're right, issue closed.
